# See: https://taskfile.dev/api/

version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/auth/v1/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
    # cmds:
    #   - protoc --go_out=gen --go-grpc_out=gen \
    #     --proto_path=proto \
    #     proto/auth/v1/auth.proto
